# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vague', models.CharField(choices=[('m3', 'M+3'), ('m6', 'M+6'), ('m12', 'M+12')], max_length=3)),
                ('date_suivi', models.DateField()),
                ('enqueteur', models.CharField(blank=True, max_length=150)),
                ('issue_contact', models.CharField(choices=[('joint', 'Joint'), ('injoignable', 'Injoignable'), ('numero_errone', 'Numéro erroné'), ('refus', 'Refus')], max_length=20)),
                ('situation_actuelle', models.CharField(blank=True, choices=[('emploi_salarie', 'Emploi salarié'), ('auto_emploi', 'Auto-emploi'), ('stage', 'Stage'), ('en_formation', 'En formation'), ('en_recherche', 'En recherche'), ('inactif', 'Inactif')], max_length=20)),
                ('type_contrat', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('journalier', 'Journalier'), ('independant', 'Indépendant')], max_length=20)),
                ('secteur_activite', models.CharField(blank=True, max_length=150)),
                ('date_debut_activite', models.DateField(blank=True, null=True)),
                ('tranche_revenu', models.CharField(blank=True, choices=[('lt_30000', '< 30 000 DJF'), ('30000_60000', '30 000 - 60 000 DJF'), ('60000_100000', '60 000 - 100 000 DJF'), ('gt_100000', '> 100 000 DJF')], max_length=20)),
                ('lien_formation', models.CharField(blank=True, choices=[('direct', 'Direct'), ('partiel', 'Partiel'), ('aucun', 'Aucun')], max_length=20)),
                ('obstacle_principal', models.TextField(blank=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='beneficiaires.beneficiaire')),
            ],
            options={
                'ordering': ['-date_suivi'],
                'unique_together': {('beneficiaire', 'vague')},
            },
        ),
    ]
