# Generated by Django 6.0.5 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
        ('suivis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='beneficiaires.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='date_debut_activite',
            field=models.DateField(blank=True, null=True, verbose_name="Date de début d'activité"),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='date_suivi',
            field=models.DateField(verbose_name='Date du contact'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='enqueteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Enquêteur'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='issue_contact',
            field=models.CharField(choices=[('joint', 'Joint'), ('injoignable', 'Injoignable'), ('numero_errone', 'Numéro erroné'), ('refus', 'Refus')], max_length=20, verbose_name='Issue du contact'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='lien_formation',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('partiel', 'Partiel'), ('aucun', 'Aucun')], max_length=20, verbose_name='Lien avec la formation'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='obstacle_principal',
            field=models.TextField(blank=True, verbose_name='Principal obstacle rencontré'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=150, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='situation_actuelle',
            field=models.CharField(blank=True, choices=[('emploi_salarie', 'Emploi salarié'), ('auto_emploi', 'Auto-emploi'), ('stage', 'Stage'), ('en_formation', 'En formation'), ('en_recherche', 'En recherche'), ('inactif', 'Inactif')], max_length=20, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='tranche_revenu',
            field=models.CharField(blank=True, choices=[('lt_30000', '< 30 000 DJF'), ('30000_60000', '30 000 - 60 000 DJF'), ('60000_100000', '60 000 - 100 000 DJF'), ('gt_100000', '> 100 000 DJF')], max_length=20, verbose_name='Tranche de revenu'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('journalier', 'Journalier'), ('independant', 'Indépendant')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='vague',
            field=models.CharField(choices=[('m3', 'M+3'), ('m6', 'M+6'), ('m12', 'M+12')], max_length=3, verbose_name='Vague de suivi'),
        ),
    ]
