# Generated by Django 6.0.5 on 2026-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0002_alter_suivi_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='canal',
            field=models.CharField(blank=True, choices=[('telephone', 'Appel téléphonique'), ('visite', 'Visite'), ('structure', 'Remontée de la structure de formation')], max_length=20, verbose_name='Canal du contact'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='demarches',
            field=models.CharField(blank=True, help_text='Codes séparés par un espace, au format brut des questions à choix multiples Kobo.', max_length=200, verbose_name='Démarches entreprises'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='duree_recherche_mois',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de recherche (mois)'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='type_activite',
            field=models.CharField(blank=True, choices=[('commerce', 'Commerce'), ('artisanat', 'Artisanat'), ('services', 'Services'), ('agriculture_peche', 'Agriculture ou pêche'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'activité (auto-emploi)"),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='issue_contact',
            field=models.CharField(choices=[('joint', 'Joint'), ('injoignable', 'Injoignable après trois tentatives'), ('numero_errone', 'Numéro erroné'), ('refus', 'Refus de répondre')], max_length=20, verbose_name='Issue du contact'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='secteur_activite',
            field=models.CharField(blank=True, choices=[('commerce', 'Commerce'), ('batiment', 'Bâtiment et travaux publics'), ('administration', 'Administration publique'), ('telecom', 'Télécommunications et numérique'), ('transport', 'Transport et logistique'), ('hotellerie', 'Hôtellerie et restauration'), ('sante_education', 'Santé ou éducation'), ('banque', 'Banque et assurance'), ('artisanat', 'Artisanat'), ('autre', 'Autre secteur')], max_length=20, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='situation_actuelle',
            field=models.CharField(blank=True, choices=[('emploi', 'Emploi salarié'), ('auto_emploi', 'Auto-emploi'), ('stage', 'Stage'), ('formation', 'Reparti en formation'), ('recherche', "En recherche d'emploi"), ('inactif', 'Sans activité et sans recherche')], max_length=20, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='tranche_revenu',
            field=models.CharField(blank=True, choices=[('moins_30k', '< 30 000 DJF'), ('30_60k', '30 000 - 60 000 DJF'), ('60_100k', '60 000 - 100 000 DJF'), ('plus_100k', '> 100 000 DJF'), ('refus', 'Ne souhaite pas répondre')], max_length=20, verbose_name='Tranche de revenu'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('journalier', 'Travail journalier'), ('stage_convention', 'Stage conventionné')], max_length=20, verbose_name='Type de contrat'),
        ),
    ]
