# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('saisie', 'Saisie'), ('validateur', 'Validateur'), ('consultation', 'Consultation')], default='consultation', max_length=20)),
                ('institution', models.ForeignKey(blank=True, help_text='Institution de rattachement. Laisser vide pour un accès multi-institutions (administrateur, ONEQ, Direction des Projets).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='referentiels.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
