# Generated by Django 6.0.5 on 2026-09-09 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('referentiels', '0002_alter_cycleenquete_options_alter_institution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institution de rattachement. Laisser vide pour un accès multi-institutions (administrateur, ONEQ, Direction des Projets).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='referentiels.institution', verbose_name='Institution de rattachement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('saisie', 'Saisie'), ('validateur', 'Validateur'), ('consultation', 'Consultation')], default='consultation', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
