# Generated by Django 6.0.5 on 2026-09-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_profile_options_alter_profile_institution_and_more'),
        ('referentiels', '0004_dgfp_remplace_eftp_et_retrait_oneq_direction_projets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institution de rattachement. Laisser vide pour un accès multi-institutions (administrateur notamment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='referentiels.institution', verbose_name='Institution de rattachement'),
        ),
    ]
