# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut_formation', models.CharField(choices=[('en_cours', 'En cours'), ('achevee', 'Achevée'), ('abandonnee', 'Abandonnée')], default='en_cours', max_length=20)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='beneficiaires.beneficiaire')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
