# Generated by Django 6.0.5 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='beneficiaires.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='domaine',
            field=models.CharField(max_length=150, verbose_name='Domaine / spécialité'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='statut_formation',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('achevee', 'Achevée'), ('abandonnee', 'Abandonnée')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
    ]
