# Generated by Django 6.0.5 on 2026-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_formation_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='centre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Centre de formation'),
        ),
    ]
