# Generated by Django 6.0.5 on 2026-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formation_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
