# Generated by Django 6.0.5 on 2026-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_alter_formation_date_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='domaine',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domaine / spécialité'),
        ),
    ]
