# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_prof', models.CharField(choices=[('emploi_salarie', 'Emploi salarié'), ('auto_emploi', 'Auto-emploi'), ('stage', 'Stage'), ('en_recherche', 'En recherche')], max_length=20)),
                ('date_insertion', models.DateField()),
                ('delai_insertion_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='beneficiaires.beneficiaire')),
            ],
            options={
                'ordering': ['-date_insertion'],
            },
        ),
    ]
