# Generated by Django 6.0.5 on 2026-09-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion',
            name='intitule_poste',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='insertion',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='date_insertion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
