# Generated by Django 6.0.5 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
        ('insertions', '0002_insertion_intitule_poste_insertion_secteur_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertions', to='beneficiaires.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='date_insertion',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'insertion"),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='delai_insertion_mois',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Délai d'insertion (mois)"),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='intitule_poste',
            field=models.CharField(blank=True, max_length=150, verbose_name='Intitulé du poste'),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=150, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='situation_prof',
            field=models.CharField(choices=[('emploi_salarie', 'Emploi salarié'), ('auto_emploi', 'Auto-emploi'), ('stage', 'Stage'), ('en_recherche', 'En recherche')], max_length=20, verbose_name='Situation professionnelle'),
        ),
    ]
