# Generated by Django 6.0.5 on 2026-09-06 11:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id_beneficiaire', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('tranche_age', models.CharField(blank=True, editable=False, max_length=10)),
                ('region', models.CharField(choices=[('djibouti', 'Djibouti'), ('ali_sabieh', 'Ali Sabieh'), ('arta', 'Arta'), ('dikhil', 'Dikhil'), ('tadjourah', 'Tadjourah'), ('obock', 'Obock')], max_length=30)),
                ('date_enregistrement', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('abandon', 'Abandon'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaires', to='referentiels.institution')),
            ],
            options={
                'ordering': ['-date_enregistrement'],
                'indexes': [models.Index(fields=['nom', 'prenom', 'date_naissance'], name='beneficiair_nom_d56774_idx')],
            },
        ),
    ]
