# Generated by Django 6.0.5 on 2026-09-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='id_beneficiaire',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
