# Generated by Django 6.0.5 on 2026-09-08 18:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0002_beneficiaire_email_beneficiaire_telephone_and_more'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_enregistrement',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='id_beneficiaire',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaires', to='referentiels.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='region',
            field=models.CharField(choices=[('djibouti', 'Djibouti'), ('ali_sabieh', 'Ali Sabieh'), ('arta', 'Arta'), ('dikhil', 'Dikhil'), ('tadjourah', 'Tadjourah'), ('obock', 'Obock')], max_length=30, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('abandon', 'Abandon'), ('archive', 'Archivé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='tranche_age',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name="Tranche d'âge"),
        ),
    ]
