# Generated by Django 6.0.5 on 2026-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceannuelle',
            options={'verbose_name': "Compteur annuel d'identifiants", 'verbose_name_plural': "Compteurs annuels d'identifiants"},
        ),
        migrations.AlterField(
            model_name='sequenceannuelle',
            name='annee',
            field=models.PositiveIntegerField(unique=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='sequenceannuelle',
            name='dernier_numero',
            field=models.PositiveIntegerField(default=0, verbose_name='Dernier numéro attribué'),
        ),
    ]
