# Generated by Django 6.0.5 on 2026-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0004_alter_sequenceannuelle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier / localité'),
        ),
    ]
