# Generated by Django 6.0.5 on 2026-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0005_beneficiaire_niveau_etude_beneficiaire_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
    ]
