# Generated by Django 6.0.5 on 2026-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('eftp', 'EFTP'), ('inap', 'INAP'), ('anefip', 'ANEFIP'), ('oneq', 'ONEQ'), ('direction_projets', 'Direction des Projets (MENFOP)'), ('autre', 'Autre')], max_length=30)),
                ('region', models.CharField(choices=[('djibouti', 'Djibouti'), ('ali_sabieh', 'Ali Sabieh'), ('arta', 'Arta'), ('dikhil', 'Dikhil'), ('tadjourah', 'Tadjourah'), ('obock', 'Obock')], max_length=30)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
    ]
