# Generated by Django 6.0.5 on 2026-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycleenquete',
            options={'ordering': ['date_debut'], 'verbose_name': "Cycle d'enquête", 'verbose_name_plural': "Cycles d'enquête"},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['libelle'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterField(
            model_name='cycleenquete',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='cycleenquete',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='cycleenquete',
            name='libelle',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='libelle',
            field=models.CharField(max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='region',
            field=models.CharField(choices=[('djibouti', 'Djibouti'), ('ali_sabieh', 'Ali Sabieh'), ('arta', 'Arta'), ('dikhil', 'Dikhil'), ('tadjourah', 'Tadjourah'), ('obock', 'Obock')], max_length=30, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('eftp', 'EFTP'), ('inap', 'INAP'), ('anefip', 'ANEFIP'), ('oneq', 'ONEQ'), ('direction_projets', 'Direction des Projets (MENFOP)'), ('autre', 'Autre')], max_length=30, verbose_name='Type'),
        ),
    ]
