# Generated by Django 6.0.5 on 2026-09-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0002_alter_cycleenquete_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('dgfp', 'DGFP'), ('inap', 'INAP'), ('anefip', 'ANEFIP'), ('autre', 'Autre')], max_length=30, verbose_name='Type'),
        ),
    ]
