# Generated by Django 6.0.5 on 2026-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_formulaire', models.CharField(choices=[('suivi', 'Suivi'), ('satisfaction', 'Satisfaction bénéficiaire'), ('satisfaction_institution', 'Satisfaction institutionnelle')], max_length=30)),
                ('kobo_submission_id', models.CharField(max_length=50)),
                ('donnees_brutes', models.JSONField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('integre', 'Intégré'), ('doublon', 'Doublon détecté'), ('erreur', 'Erreur')], default='nouveau', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recu_le'],
                'unique_together': {('type_formulaire', 'kobo_submission_id')},
            },
        ),
    ]
