# Generated by Django 6.0.5 on 2026-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobosoumission',
            options={'ordering': ['-recu_le'], 'verbose_name': 'Soumission Kobo', 'verbose_name_plural': 'Soumissions Kobo'},
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='donnees_brutes',
            field=models.JSONField(verbose_name='Données brutes'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='erreur',
            field=models.TextField(blank=True, verbose_name='Erreur'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='kobo_submission_id',
            field=models.CharField(max_length=50, verbose_name='Identifiant de soumission Kobo'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='recu_le',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reçu le'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('integre', 'Intégré'), ('doublon', 'Doublon détecté'), ('erreur', 'Erreur')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='traite_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='type_formulaire',
            field=models.CharField(choices=[('suivi', 'Suivi'), ('satisfaction', 'Satisfaction bénéficiaire'), ('satisfaction_institution', 'Satisfaction institutionnelle')], max_length=30, verbose_name='Type de formulaire'),
        ),
    ]
