# Generated by Django 6.0.5 on 2026-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_kobosoumission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobosoumission',
            name='type_formulaire',
            field=models.CharField(choices=[('suivi', 'Suivi et satisfaction bénéficiaire'), ('satisfaction_institution', 'Satisfaction institutionnelle')], max_length=30, verbose_name='Type de formulaire'),
        ),
    ]
