# Generated by Django 6.0.5 on 2026-09-28 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_kobosoumission_type_formulaire'),
        ('referentiels', '0002_alter_cycleenquete_options_alter_institution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kobosoumission',
            name='donnees_corrigees',
            field=models.JSONField(blank=True, null=True, verbose_name='Données corrigées'),
        ),
        migrations.AddField(
            model_name='kobosoumission',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_kobo', to='referentiels.institution', verbose_name='Institution concernée'),
        ),
        migrations.AddField(
            model_name='kobosoumission',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='kobosoumission',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'À valider'), ('integre', 'Intégré'), ('doublon', 'Écartée'), ('erreur', 'Erreur')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
    ]
