# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_certificat', models.CharField(max_length=150)),
                ('date_certification', models.DateField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='beneficiaires.beneficiaire')),
            ],
            options={
                'ordering': ['-date_certification'],
            },
        ),
    ]
