# Generated by Django 6.0.5 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='beneficiaires.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_certification',
            field=models.DateField(verbose_name='Date de certification'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='type_certificat',
            field=models.CharField(max_length=150, verbose_name='Type de certificat'),
        ),
    ]
