# Generated by Django 6.0.5 on 2026-09-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_formation', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_formateurs', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_contenus', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_equipements', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_accueil', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('points_positifs', models.TextField(blank=True)),
                ('points_a_ameliorer', models.TextField(blank=True)),
                ('amelioration_employabilite', models.CharField(choices=[('tout_a_fait', 'Tout à fait'), ('plutot', 'Plutôt'), ('peu', 'Peu'), ('pas_du_tout', 'Pas du tout')], max_length=20)),
                ('recommande', models.BooleanField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='beneficiaires.beneficiaire')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='referentiels.cycleenquete')),
            ],
            options={
                'ordering': ['-cycle__date_debut'],
                'unique_together': {('beneficiaire', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='SatisfactionInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_formation', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_formateurs', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_contenus', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_equipements', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note_accueil', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('points_positifs', models.TextField(blank=True)),
                ('points_a_ameliorer', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions_institution', to='referentiels.cycleenquete')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions_institution', to='referentiels.institution')),
            ],
            options={
                'ordering': ['-cycle__date_debut'],
                'unique_together': {('institution', 'cycle')},
            },
        ),
    ]
