# Generated by Django 6.0.5 on 2026-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_alter_beneficiaire_date_enregistrement_and_more'),
        ('referentiels', '0001_initial'),
        ('satisfactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfaction',
            name='amelioration_employabilite',
            field=models.CharField(choices=[('tout_a_fait', 'Tout à fait'), ('plutot', 'Plutôt'), ('peu', 'Peu'), ('pas_du_tout', 'Pas du tout')], max_length=20, verbose_name="Amélioration de l'employabilité"),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='beneficiaires.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='referentiels.cycleenquete', verbose_name="Cycle d'enquête"),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_accueil',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note accueil'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_contenus',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note contenus'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_equipements',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note équipements'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formateurs',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formateurs'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formation'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='points_a_ameliorer',
            field=models.TextField(blank=True, verbose_name='Points à améliorer'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='points_positifs',
            field=models.TextField(blank=True, verbose_name='Points positifs'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='recommande',
            field=models.BooleanField(verbose_name='Recommande la formation'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions_institution', to='referentiels.cycleenquete', verbose_name="Cycle d'enquête"),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions_institution', to='referentiels.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_accueil',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note accueil'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_contenus',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note contenus'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_equipements',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note équipements'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_formateurs',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formateurs'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_formation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formation'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='points_a_ameliorer',
            field=models.TextField(blank=True, verbose_name='Points à améliorer'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='points_positifs',
            field=models.TextField(blank=True, verbose_name='Points positifs'),
        ),
    ]
