# Generated by Django 6.0.5 on 2026-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfactions', '0002_alter_satisfaction_amelioration_employabilite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satisfactioninstitution',
            options={'ordering': ['-cycle__date_debut'], 'verbose_name': 'Satisfaction institutionnelle', 'verbose_name_plural': 'Satisfactions institutionnelles'},
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='note_accueil',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='note_contenus',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='note_equipements',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='note_formateurs',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='note_formation',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='points_a_ameliorer',
        ),
        migrations.RemoveField(
            model_name='satisfactioninstitution',
            name='points_positifs',
        ),
        migrations.AddField(
            model_name='satisfaction',
            name='raison_non_recommande',
            field=models.TextField(blank=True, verbose_name='Raison (si ne recommande pas)'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='date_reponse',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la réponse'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='difficultes',
            field=models.TextField(blank=True, verbose_name='Difficultés rencontrées'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='fonction_repondant',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fonction du répondant'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='note_appui_technique',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Appui technique reçu'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='note_coordination',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Coordination entre les structures'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='note_outils_collecte',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Outils de collecte mis à disposition'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='note_qualite_donnees',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Qualité et fiabilité des données'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='note_tableaux_bord',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Utilité des tableaux de bord'),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='recommandations',
            field=models.TextField(blank=True, verbose_name="Recommandations d'amélioration"),
        ),
        migrations.AddField(
            model_name='satisfactioninstitution',
            name='utilite_dispositif',
            field=models.CharField(choices=[('pleinement', 'Pleinement'), ('partiellement', 'Partiellement'), ('peu', 'Peu'), ('pas_du_tout', 'Pas du tout')], default='pleinement', max_length=20, verbose_name='Le dispositif répond-il aux besoins de la structure ?'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_accueil',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name="Note conditions d'accueil"),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_contenus',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Note contenus'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_equipements',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Note équipements'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formateurs',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Note formateurs'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Note formation'),
        ),
    ]
