# Generated by Django 6.0.5 on 2026-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfactions', '0003_alter_satisfactioninstitution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfaction',
            name='note_accueil',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name="Note conditions d'accueil"),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_contenus',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note contenus'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_equipements',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note équipements'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formateurs',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formateurs'),
        ),
        migrations.AlterField(
            model_name='satisfaction',
            name='note_formation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note formation'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_appui_technique',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Appui technique reçu'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_coordination',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Coordination entre les structures'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_outils_collecte',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Outils de collecte mis à disposition'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_qualite_donnees',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Qualité et fiabilité des données'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='note_tableaux_bord',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Utilité des tableaux de bord'),
        ),
        migrations.AlterField(
            model_name='satisfactioninstitution',
            name='utilite_dispositif',
            field=models.CharField(choices=[('pleinement', 'Pleinement'), ('partiellement', 'Partiellement'), ('peu', 'Peu'), ('pas_du_tout', 'Pas du tout')], max_length=20, verbose_name='Le dispositif répond-il aux besoins de la structure ?'),
        ),
    ]
